path:
  data_root: "/Users/milla/Documents/dataset"
  label_root: "/Users/milla/Documents/dataset/labels"
  pcd_root: "/Users/milla/Documents/dataset/pointclouds"
  exp_path: "/Users/milla/Documents/pcd_ground_segmentation/experiments"
  split: # sequence numbers
    train:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 9
      - 10
    valid:
      - 8
    test:
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21

encoder:
  H: 3 # z normalization constant
  R_unit: 0.5 # divided bins(unit=m)
  C: 90 # divided cones (unit=pcs)

pointcloud:
  target_range: [30, -3, 5] # [radius z_min z_max]
  
learn:
  total_epoch: 100
  save_interval: 2
  batch_size: 4
  

model:
  # https://github.com/martin-velas/but_velodyne_cnn/blob/master/networks/L03-deconv-inc-multich/net_train_val.prototxt
  loss: "BCEWithLogtisLoss"
