path:
  data_root: "/home/ext/SemanticKITTI/dataset"
  label_root: "/home/ext/SemanticKITTI/dataset"
  pcd_root: "/home/ext/SemanticKITTI/dataset"
  exp_path: "/home/datalab/Milla/pcd_ground_segmentation/experiments/tmp"
  log_path: "/home/datalab/Milla/pcd_ground_segmentation/experiments/tmp"
  split: # sequence
    train:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 9
      - 10
    valid:
      - 8
    test:
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21

encoder:
  H: 1 # z normalization constant
  R_unit: 0.5 # divided bins(unit=m)
  C: 360 # divided cones (unit=pcs)

pointcloud:
  target_range: [50, -3, 5] # [radius z_min z_max]
  
learn:
  total_epoch: 20
  save_interval: 10
  batch_size: 8
  #lr: 0.0005
  #weight_decay: 0.1
  lr: 0.0001
  weight_decay: 0.9
  milestones: [18, 19]
  

augmentation:
  height: [-3, 3]
  flip: True
  prob: 0.5


model:
  # https://github.com/martin-velas/but_velodyne_cnn/blob/master/networks/L03-deconv-inc-multich/net_train_val.prototxt
  loss: "SoftmaxWithloss" #SoftmaxWithloss" #MSE  #FocalLoss

tmp:
  load_train_data_interval: 0

eval:
  vis_interval: 100
  vis_path: 'eval_vis'