path:
  data_root: "/home/ext/SemanticKITTI/dataset"
  label_root: "/home/ext/SemanticKITTI/dataset"
  pcd_root: "/home/ext/SemanticKITTI/dataset"
  exp_path: "/home/datalab/Milla/pcd_ground_segmentation/experiments/tmp"
  log_path: "/home/datalab/Milla/pcd_ground_segmentation/experiments/tmp"
  split: # sequence
    train:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 9
      - 10
    valid:
      - 8
    test:
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21

encoder:
  H: 1 # z normalization constant
  R_unit: 0.5 # divided bins(unit=m)
  C: 360 # divided cones (unit=pcs)

pointcloud:
  target_range: [30, -3, 5] # [radius z_min z_max] 
  
learn:
  total_epoch: 20
  save_interval: 10
  batch_size: 8
  lr: 0.0001
  weight_decay: 0.9
  milestones: [18, 19]
  

augmentation:
  height: [-3, 3] # minmax values to be added to the z-axis
  flip: True # x or y-axis flip
  prob: 0.5


model:
  loss: "SoftmaxWithloss" #MSE  #FocalLoss

#tmp:
#  load_train_data_interval: 400

eval:
  vis_interval: 50
  vis_path: 'eval_vis'